name: LobbyManager
main: io.github.mac_genius.lobbymanager.LobbyManager
version: 1.0
permissions:
    scoreboardmaster.*:
        description: Gives access to all commands for the plugin
        children:
            scoreboardmaster.reload: true
            scoreboardmaster.help: true

    scoreboardmaster.reload:
        description: Allows a player to reload the config
        default: op
    scoreboardmaster.help:
        description: Brings up the commands
        default: op
commands:
    sm:
        description: This is the help command.
        usage: /sm
        permission: lobbymanager.help
        permission-message: You do not have permission to do that.
    sm reload:
            description: This will reload the plugin.
            usage: /sm reload
            permission: lobbymanager.reload
            permission-message: You do not have permission to do that.
    sstop:
                description: This will stop the server.
                usage: /sstop
                permission: lobbymanager.stop
                permission-message: You do not have permission to do that.