name: LobbyManager
main: io.github.mac_genius.lobbymanager.LobbyManager
version: 1.0
softdepend: [SQLPermissions, SQLEconomy]
permissions:
    lobbymanager.*:
        description: Gives access to all commands for the plugin
        children:
            lobbymanager.reload: true
            lobbymanager.help: true
            lobbymanager.stop: true
            lobbymanager.createtext: true
            lobbymanager.whitelist: true
            lobbymanager.build: true
            lobbymanager.break: true
            lobbymanager.drop: true
            lobbymanager.click: true
            lobbymanager.test: true

    lobbymanager.reload:
        description: Allows a player to reload the config
        default: op
    lobbymanager.help:
        description: Brings up the commands
        default: op
    lobbymanager.stop:
        description: Stops the server safely
        default: op
    lobbymanager.createtext:
        description: Allows players to create text
        default: op
    lobbymanager.whitelist:
        description: Allows players to manage the whitelist
        default: op
    lobbymanager.build:
        description: Allows players to build
        default: op
    lobbymanager.break:
        description: Allows players to break stuff
        default: op
    lobbymanager.drop:
        description: Allows players to drop stuff
        default: op
    lobbymanager.click:
        description: Allows players to click items
        default: op
    lobbymanager.test:
        description: Allows players to connect to test servers
        default: op
commands:
    sm:
        description: This is the help command.
        usage: /sm
        permission: lobbymanager.help
        permission-message: You do not have permission to do that.
    sm reload:
        description: This will reload the plugin.
        usage: /sm reload
        permission: lobbymanager.reload
        permission-message: You do not have permission to do that.
    sstop:
        description: This will stop the server.
        usage: /sstop
        permission: lobbymanager.stop
        permission-message: You do not have permission to do that.
    holotext:
        description: Allows player to create text.
        usage: /holotext
        permission: lobbymanager.createtext
        permission-message: You do not have permission to do that.